-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.detail_transaksi
(
    id_detail_transaksi integer NOT NULL,
    id_transaksi integer NOT NULL,
    id_laptop integer NOT NULL,
    jumlah integer NOT NULL,
    PRIMARY KEY (id_detail_transaksi)
);

CREATE TABLE IF NOT EXISTS public.laptop
(
    id_laptop integer NOT NULL,
    nama_laptop character varying(255) NOT NULL,
    harga_laptop integer NOT NULL,
    stok integer,
    PRIMARY KEY (id_laptop)
);

CREATE TABLE IF NOT EXISTS public.transaksi
(
    id_transaksi integer NOT NULL,
    tanggal_transaksi timestamp without time zone NOT NULL,
    bayar integer NOT NULL,
    PRIMARY KEY (id_transaksi)
);

ALTER TABLE public.detail_transaksi
    ADD FOREIGN KEY (id_laptop)
    REFERENCES public.laptop (id_laptop)
    NOT VALID;


ALTER TABLE public.detail_transaksi
    ADD FOREIGN KEY (id_transaksi)
    REFERENCES public.transaksi (id_transaksi)
    NOT VALID;

END;